name: Build and Release k-NN
on:
  push:
    branches:
      - opendistro-*

jobs:
  Build-k-NN:
    strategy:
      matrix:
        java: [12]

    name: Build and Release k-NN Plugin
    runs-on: ubuntu-latest

    steps:
      - name: Checkout k-NN
        uses: actions/checkout@v1
        
      - name: Setup Java ${{ matrix.java }}
        uses: actions/setup-java@v1
        with:
          java-version: ${{ matrix.java }}
      
      - name: Run build
        run: |
          ./gradlew build
